backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: /img
site_url: 'pak-catur.netlify.app'
collections:
  - label: 'Materi'
    name: 'materi'
    folder: 'materi'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'soal'
    folder: 'soal'
    label: 'Soal'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Soal'
        name: 'soal'
        widget: 'list'
        max: 10
        fields:
          - { label: 'Pertanyaan', widget: 'string', name: 'pertanyaan' }
          - label: 'Foto Tambahan'
            widget: 'image'
            name: 'fotoTambahan'
            required: false
          - label: 'Daftar Jawaban'
            widget: 'list'
            name: 'daftarJawaban'
            max: 5
            fields:
              - { label: 'Jawaban', name: 'jawaban', widget: 'string' }
              - label: 'Foto Tambahan'
                widget: 'image'
                name: 'fotoTambahan'
                required: false
              - label: 'Jawaban Benar?'
                name: 'trueKah'
                widget: 'boolean'
                default: false
