backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: public/img/content
public_folder: /img/content
site_url: 'https://erickchristian.netlify.app/'
collections:
  - label: 'Blogs'
    name: 'blogs'
    folder: 'contents/blogs'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: Date
        name: date
        format: 'DD MMM YYYY'
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Index Page'
        name: 'index'
        file: 'contents/index.md'
        fields:
          - label: Body
            name: body
            widget: markdown
      - label: 'Notes Page'
        name: 'notes'
        file: 'contents/notes.md'
        fields:
          - label: Body
            name: body
            widget: markdown
